= flexidesk API 문서
flexidesk API 명세서입니다
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left
:toclevels: 2
:sectlinks:

[[Reservation-API]]
== 예약 API

[[POST-Reservation]]
=== 예약 등록
operation::post-reservation[]


[[GET-All-Reservations]]
=== 전체 예약 조회
operation::get-all-reservations[]


[[GET-Reservation-Timetable]]
=== 회의실 당일 예약 타임테이블 조회
operation::get-all-reservations[]

[[GET-User-Reservation]]
=== 회원 개인의 전체 예약 조회
operation::get-user-reservations[]

[[PATCH-Reservation]]
=== 예약 수정
operation::patch-reservation[]


[[DELETE-Reservation]]
=== 예약 삭제
operation::delete-reservation[]


[[DELETE-Reservation-MeetingRoom]]
=== 예약 내 회의실 정보 삭제
operation::delete-reservation-meetingroom[]


[[Schedule-API]]
== 스케줄 API

[[GET-All-Schedules]]
=== 전체 스케줄 조회
operation::get-all-schedules[]

[[GET-Schedules-Timetable]]
=== 당일 스케줄 조회
operation::get-schedule-timetable[]

[[POST-Schedules]]
=== 스케줄 등록
operation::post-schedule[]

[[PATCH-Schedules]]
=== 스케줄 수정
operation::patch-schedule[]


[[Box-API]]
== Box API

[[POST-Box]]
=== 박스 생성
operation::post-createBox[]

[[PATCH-Box]]
=== 박스 수정
operation::patch-updateBox[]

[[DELETE-Box]]
=== 박스 삭제
operation::delete-deleteBox[]

[[Floor-API]]
== Floor API

[[POST-Floor]]
=== floor 생성
operation::post-createFloor[]

[[PATCH-Floor]]
=== floor 수정
operation::patch-updateFloor[]

[[DELETE-Floor]]
=== floor 삭제
operation::delete-deleteFloor[]

[[GET-Floorlist]]
=== floor 선택 조회
operation::get-getFloorlist[]

[[GET-Floor]]
=== Floor 전체 조회
operation::get-getFloor[]

[[Mr-API]]
== Mr API

[[POST-Mr]]
=== Mr 생성
operation::post-createMr[]

[[PATCH-Mr]]
=== Mr 수정
operation::patch-updateMr[]

[[DELETE-Mr]]
=== Mr 삭제
operation::delete-deleteMr[]

[[GET-MR]]
=== Mr 전체조회
operation::get-mrlist[]

[[MultiBox-API]]
== MultiBox API

[[POST-MultiBox]]
=== MultiBox 생성
operation::post-createMultiBox[]

[[PATCH-MultiBox]]
=== MultiBox 수정
operation::patch-updateMultiBox[]

[[DELETE-MultiBox]]
=== MultiBox 삭제
operation::delete-deleteMultiBox[]

[[Space-API]]
== Space API

[[POST-Space]]
=== Space 생성
operation::post-createSpace[]

[[POST-Spaceinfloor]]
=== Space Floor 생성
operation::post-createSpaceinfloor[]

[[GET-Space]]
=== Space 전체 조회
operation::get-allSpacelist[]

[[GET-Spacelist]]
=== Space 선택 조회
operation::get-getSpacelist[]

[[PATCH-Space]]
=== Space 수정
operation::patch-updateSpace[]

[[DELETE-Space]]
=== Space 삭제
operation::delete-deleteSpace[]

[[Location-API]]
== Location API

[[PATCH-Location]]
=== Location 유저 이동
operation::patch-moveWithUser[]

[[User-API]]
== User API

[[POST-Admin]]
=== 관리자 회원 가입
operation::post-signupAdmin[]

[[POST-User]]
=== 사원 회원 가입
operation::post-signupUser[]

[[POST-Email]]
=== Email 발송
operation::post-signup-email[]

[[GET-certification]]
=== 인증번호 확인
operation::post-users-signup-match[]

[[GET-User-Search-Result]]
=== 유저 검색
operation::get-user-search-result[]

[[POST-login]]
=== login
operation::post-users-login[]

[[Admin-API]]
== Admin API

[[GET-getAllUsers]]
=== 사원 목록 조회
operation::get-all-userList[]

[[GET-getUsers]]
=== 사원 선택 조회
operation::get-user[]

[[PATCH-editUser]]
=== 사원 권한 수정
operation::patch-user-role[]

[[DELETE-deleteUser]]
=== 사원 삭제
operation::delete-user[]